### ISSUE TITLE
Prediction fails with "TypeError: int() argument must be a string [...], not 'map'" on Python 3

### ISSUE THREAD

**Issue by sarnthil** [ichuang/tflearn_seq2seq#3]
```
[TFLearnSeq2Seq] model weights loaded from weights.tfl
Xin = <map object at 0x11a33bcc0>
Traceback (most recent call last):
  File "tflearn_seq2seq.py", line 538, in <module>
    CommandLine()
  File "tflearn_seq2seq.py", line 377, in CommandLine
    prediction, y = ts2s.predict(x, weights_input_fn=args.input_weights, model_params=model_params)
  File "tflearn_seq2seq.py", line 272, in predict
    X = np.array(Xin).astype(np.uint32)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'map'
```

The problem lies in line 368, because `map` returns a map object in Python 3, not a list.

Wrapping `list()` around the map object restores the correct behaviour in Python 3, while being backwards-compatible to Python 2:

```
input_x = list(map(int, args.cmd_input))
```

**Comment by ichuang** [comment]
Thanks!  Fixed.
